import { PROVIDER_PROFILE_OPTIONS } from "./providerCatalog";
import type { AgentFieldDefinition } from "./agentConfig";

export type TeamFieldDefinition = AgentFieldDefinition;

export const TEAM_FIELDS: TeamFieldDefinition[] = [
  { key: "name", label: "Name", type: "text", group: "Identity", required: true },
  { key: "role", label: "Team Role", type: "text", group: "Identity", placeholder: "research_lead" },
  { key: "description", label: "Description", type: "textarea", group: "Prompt" },
  {
    key: "provider_profile",
    label: "Provider Preset",
    type: "select",
    group: "Providers",
    helper: "Applies the provider catalog defaults for the team leader model.",
    options: PROVIDER_PROFILE_OPTIONS,
  },
  { key: "provider", label: "Provider", type: "text", group: "Providers", placeholder: "openai" },
  { key: "model", label: "Model", type: "text", group: "Providers", placeholder: "gpt-4.1-mini" },
  {
    key: "provider_api_key_env",
    label: "API Key Env Var",
    type: "text",
    group: "Providers",
    helper: "Optional override for the team model API key env var.",
    placeholder: "OPENAI_API_KEY",
  },
  {
    key: "provider_api_key",
    label: "API Key",
    type: "text",
    group: "Providers",
    helper: "Optional. If empty, the team uses the system environment.",
    placeholder: "sk-...",
  },
  {
    key: "provider_base_url_env",
    label: "Base URL Env Var",
    type: "text",
    group: "Providers",
    helper: "Optional override for providers that need a custom endpoint env var.",
    placeholder: "OPENAI_BASE_URL",
  },
  {
    key: "provider_base_url",
    label: "Base URL",
    type: "text",
    group: "Providers",
    helper: "Optional. Leave empty for the provider default routing.",
    placeholder: "https://api.openai.com/v1",
  },
  {
    key: "provider_execution_timeout_seconds",
    label: "Execution Timeout Seconds",
    type: "number",
    group: "Providers",
    helper: "Optional. Increase this for slower local providers like Ollama.",
    placeholder: "120",
  },
  {
    key: "provider_env_json",
    label: "Extra Env JSON",
    type: "json",
    group: "Providers",
    helper: "Optional extra environment variables for the team leader model.",
    placeholder: '{\n  "AWS_REGION": "us-east-1"\n}',
  },
  { key: "instructions", label: "Instructions", type: "textarea", group: "Prompt", required: true },
  { key: "system_message", label: "System Message", type: "textarea", group: "Prompt" },
  { key: "system_message_role", label: "System Message Role", type: "text", group: "Prompt", placeholder: "system" },
  { key: "introduction", label: "Introduction", type: "textarea", group: "Prompt" },
  { key: "expected_output", label: "Expected Output", type: "textarea", group: "Prompt" },
  { key: "additional_context", label: "Additional Context", type: "textarea", group: "Prompt" },
  { key: "add_instruction_tags", label: "Add Instruction Tags", type: "checkbox", group: "Prompt" },
  { key: "markdown", label: "Markdown", type: "checkbox", group: "Prompt" },
  { key: "add_name_to_context", label: "Add Name To Context", type: "checkbox", group: "Prompt" },
  { key: "add_datetime_to_context", label: "Add Datetime To Context", type: "checkbox", group: "Prompt" },
  { key: "add_location_to_context", label: "Add Location To Context", type: "checkbox", group: "Prompt" },
  { key: "timezone_identifier", label: "Timezone Identifier", type: "text", group: "Prompt", placeholder: "Etc/UTC" },
  { key: "resolve_in_context", label: "Resolve In Context", type: "checkbox", group: "Prompt" },
  { key: "user_id", label: "User ID", type: "text", group: "Session" },
  { key: "session_id", label: "Session ID", type: "text", group: "Session" },
  { key: "session_state", label: "Session State", type: "json", group: "Session", placeholder: '{\n  "stage": "draft"\n}' },
  { key: "add_session_state_to_context", label: "Add Session State To Context", type: "checkbox", group: "Session" },
  { key: "enable_agentic_state", label: "Enable Agentic State", type: "checkbox", group: "Session" },
  { key: "overwrite_db_session_state", label: "Overwrite DB Session State", type: "checkbox", group: "Session" },
  { key: "cache_session", label: "Cache Session", type: "checkbox", group: "Session" },
  { key: "search_past_sessions", label: "Search Past Sessions", type: "checkbox", group: "Session" },
  { key: "num_past_sessions_to_search", label: "Past Sessions To Search", type: "number", group: "Session" },
  { key: "num_past_session_runs_in_search", label: "Past Session Runs In Search", type: "number", group: "Session" },
  { key: "search_session_history", label: "Search Session History", type: "checkbox", group: "Session" },
  { key: "num_history_sessions", label: "Num History Sessions", type: "number", group: "Session" },
  { key: "add_team_history_to_members", label: "Add Team History To Members", type: "checkbox", group: "Session" },
  { key: "num_team_history_runs", label: "Team History Runs", type: "number", group: "Session" },
  { key: "add_history_to_context", label: "Add History To Context", type: "checkbox", group: "Session" },
  { key: "num_history_runs", label: "Num History Runs", type: "number", group: "Session" },
  { key: "num_history_messages", label: "Num History Messages", type: "number", group: "Session" },
  { key: "read_chat_history", label: "Read Chat History Tool", type: "checkbox", group: "Session" },
  { key: "store_history_messages", label: "Store History Messages", type: "checkbox", group: "Session" },
  { key: "dependencies", label: "Dependencies", type: "json", group: "Memory", placeholder: '{\n  "tenant_id": "acme"\n}' },
  { key: "add_dependencies_to_context", label: "Add Dependencies To Context", type: "checkbox", group: "Memory" },
  { key: "db", label: "DB", type: "python", group: "Memory", placeholder: "db_instance" },
  { key: "memory_manager", label: "Memory Manager", type: "python", group: "Memory", placeholder: "memory_manager" },
  { key: "enable_agentic_memory", label: "Enable Agentic Memory", type: "checkbox", group: "Memory" },
  { key: "update_memory_on_run", label: "Update Memory On Run", type: "checkbox", group: "Memory" },
  { key: "add_memories_to_context", label: "Add Memories To Context", type: "checkbox", group: "Memory" },
  { key: "enable_session_summaries", label: "Enable Session Summaries", type: "checkbox", group: "Memory" },
  { key: "add_session_summary_to_context", label: "Add Session Summary To Context", type: "checkbox", group: "Memory" },
  { key: "session_summary_manager", label: "Session Summary Manager", type: "python", group: "Memory", placeholder: "summary_manager" },
  { key: "compression_manager", label: "Compression Manager", type: "python", group: "Memory", placeholder: "compression_manager" },
  { key: "compress_tool_results", label: "Compress Tool Results", type: "checkbox", group: "Memory" },
  { key: "learning_machine", label: "Learning Machine", type: "python", group: "Memory", placeholder: "learning_machine", helper: "Connect a Learning Machine node to manage learning as a reusable shared resource." },
  { key: "learning", label: "Enable Learning", type: "checkbox", group: "Memory", helper: "Quick toggle for built-in team learning when this team has a database connected." },
  { key: "add_learnings_to_context", label: "Add Learnings To Context", type: "checkbox", group: "Memory", helper: "Injects the most relevant learnings into the shared team context before the run." },
  { key: "knowledge", label: "Knowledge", type: "python", group: "Knowledge", placeholder: "knowledge_base" },
  { key: "knowledge_filters", label: "Knowledge Filters", type: "json", group: "Knowledge", placeholder: '{\n  "topic": "support"\n}' },
  { key: "enable_agentic_knowledge_filters", label: "Enable Agentic Knowledge Filters", type: "checkbox", group: "Knowledge" },
  { key: "add_knowledge_to_context", label: "Add Knowledge To Context", type: "checkbox", group: "Knowledge" },
  { key: "knowledge_retriever", label: "Knowledge Retriever", type: "python", group: "Knowledge", placeholder: "custom_retriever" },
  {
    key: "references_format",
    label: "References Format",
    type: "select",
    group: "Knowledge",
    options: [
      { label: "json", value: "json" },
      { label: "yaml", value: "yaml" },
    ],
  },
  { key: "search_knowledge", label: "Search Knowledge Tool", type: "checkbox", group: "Knowledge" },
  { key: "update_knowledge", label: "Update Knowledge Tool", type: "checkbox", group: "Knowledge" },
  {
    key: "mode",
    label: "Team Mode",
    type: "select",
    group: "Input/Output",
    options: [
      { label: "coordinate", value: "coordinate" },
      { label: "route", value: "route" },
      { label: "broadcast", value: "broadcast" },
      { label: "tasks", value: "tasks" },
    ],
  },
  { key: "respond_directly", label: "Respond Directly", type: "checkbox", group: "Input/Output" },
  { key: "determine_input_for_members", label: "Determine Input For Members", type: "checkbox", group: "Input/Output" },
  { key: "delegate_to_all_members", label: "Delegate To All Members", type: "checkbox", group: "Input/Output" },
  { key: "max_iterations", label: "Max Iterations", type: "number", group: "Input/Output" },
  { key: "reasoning", label: "Reasoning", type: "checkbox", group: "Input/Output" },
  { key: "reasoning_model", label: "Reasoning Model", type: "python", group: "Input/Output", placeholder: '"openai:gpt-4.1-mini"' },
  { key: "reasoning_agent", label: "Reasoning Agent", type: "python", group: "Input/Output", placeholder: "reasoning_agent" },
  { key: "reasoning_min_steps", label: "Reasoning Min Steps", type: "number", group: "Input/Output" },
  { key: "reasoning_max_steps", label: "Reasoning Max Steps", type: "number", group: "Input/Output" },
  { key: "send_media_to_model", label: "Send Media To Model", type: "checkbox", group: "Input/Output" },
  { key: "store_media", label: "Store Media", type: "checkbox", group: "Input/Output" },
  { key: "store_tool_messages", label: "Store Tool Messages", type: "checkbox", group: "Input/Output" },
  { key: "additional_input", label: "Additional Input", type: "json", group: "Input/Output", placeholder: '[{"role": "user", "content": "extra"}]' },
  { key: "followups", label: "Enable Followups", type: "checkbox", group: "Input/Output" },
  { key: "num_followups", label: "Number Of Followups", type: "number", group: "Input/Output" },
  { key: "tool_call_limit", label: "Tool Call Limit", type: "number", group: "Tools" },
  { key: "tool_choice", label: "Tool Choice", type: "json", group: "Tools", placeholder: '{\n  "type": "function"\n}' },
  { key: "tool_hooks", label: "Tool Hooks", type: "python", group: "Tools", placeholder: "[hook_a, hook_b]" },
  { key: "pre_hooks", label: "Pre Hooks", type: "python", group: "Tools", placeholder: "[pre_hook]" },
  { key: "post_hooks", label: "Post Hooks", type: "python", group: "Tools", placeholder: "[post_hook]" },
  { key: "add_member_tools_to_context", label: "Add Member Tools To Context", type: "checkbox", group: "Tools" },
  { key: "get_member_information_tool", label: "Get Member Information Tool", type: "checkbox", group: "Tools" },
  { key: "share_member_interactions", label: "Share Member Interactions", type: "checkbox", group: "Tools" },
  { key: "stream", label: "Stream", type: "checkbox", group: "Streaming" },
  { key: "stream_events", label: "Stream Events", type: "checkbox", group: "Streaming" },
  { key: "store_events", label: "Store Events", type: "checkbox", group: "Streaming" },
  { key: "events_to_skip", label: "Events To Skip", type: "json", group: "Streaming", placeholder: '["tool_started"]' },
  { key: "stream_member_events", label: "Stream Member Events", type: "checkbox", group: "Streaming" },
  { key: "store_member_responses", label: "Store Member Responses", type: "checkbox", group: "Streaming" },
  { key: "show_members_responses", label: "Show Members Responses", type: "checkbox", group: "Streaming" },
  { key: "metadata", label: "Metadata", type: "json", group: "Debug", placeholder: '{\n  "owner": "alexandre"\n}' },
  { key: "debug_mode", label: "Debug Mode", type: "checkbox", group: "Debug" },
  {
    key: "debug_level",
    label: "Debug Level",
    type: "select",
    group: "Debug",
    options: [
      { label: "1", value: "1" },
      { label: "2", value: "2" },
    ],
  },
  { key: "telemetry", label: "Telemetry", type: "checkbox", group: "Debug" },
];

export const TEAM_FIELD_GROUPS: TeamFieldDefinition["group"][] = [
  "Identity",
  "Providers",
  "Prompt",
  "Session",
  "Memory",
  "Knowledge",
  "Tools",
  "Input/Output",
  "Streaming",
  "Debug",
];
