export interface BuiltInToolDefinition {
  key: string;
  label: string;
  category: string;
  importPath: string;
  className: string;
  description: string;
  configTemplate?: string;
  prerequisite?: string;
}

const RAW_BUILT_IN_TOOLS: BuiltInToolDefinition[] = [
  {
    key: "websearch",
    label: "WebSearchTools",
    category: "Search",
    importPath: "agno.tools.websearch",
    className: "WebSearchTools",
    description: "Multi-backend web search using DDGS. Recommended for general research.",
    configTemplate: '{\n  "backend": "google"\n}',
    prerequisite: "pip install -U ddgs",
  },
  {
    key: "duckduckgo",
    label: "DuckDuckGoTools",
    category: "Search",
    importPath: "agno.tools.duckduckgo",
    className: "DuckDuckGoTools",
    description: "Search and news on DuckDuckGo.",
    configTemplate: '{\n  "enable_search": true,\n  "enable_news": true\n}',
    prerequisite: "pip install -U ddgs",
  },
  {
    key: "yfinance",
    label: "YFinanceTools",
    category: "Finance",
    importPath: "agno.tools.yfinance",
    className: "YFinanceTools",
    description: "Stock prices, fundamentals, and Yahoo Finance news.",
    configTemplate: '{\n  "stock_price": true,\n  "analyst_recommendations": true,\n  "company_info": true\n}',
    prerequisite: "pip install -U yfinance",
  },
  {
    key: "openbb",
    label: "OpenBBTools",
    category: "Finance",
    importPath: "agno.tools.openbb",
    className: "OpenBBTools",
    description: "Financial tools from the OpenBB ecosystem.",
  },
  {
    key: "financial_datasets",
    label: "FinancialDatasetsTools",
    category: "Finance",
    importPath: "agno.tools.financial_datasets",
    className: "FinancialDatasetsTools",
    description: "SEC filings, earnings, and financial datasets.",
  },
  {
    key: "postgres",
    label: "PostgresTools",
    category: "Database",
    importPath: "agno.tools.postgres",
    className: "PostgresTools",
    description: "Run PostgreSQL queries.",
  },
  {
    key: "duckdb",
    label: "DuckDbTools",
    category: "Database",
    importPath: "agno.tools.duckdb",
    className: "DuckDbTools",
    description: "Analytical queries with DuckDB.",
  },
  {
    key: "neo4j",
    label: "Neo4jTools",
    category: "Database",
    importPath: "agno.tools.neo4j",
    className: "Neo4jTools",
    description: "Tools for Neo4j graph databases.",
  },
  {
    key: "sql",
    label: "SQLTools",
    category: "Database",
    importPath: "agno.tools.sql",
    className: "SQLTools",
    description: "Generic SQL toolkit.",
  },
  {
    key: "csv",
    label: "CsvTools",
    category: "Database",
    importPath: "agno.tools.csv_toolkit",
    className: "CsvTools",
    description: "CSV file analysis.",
  },
  {
    key: "pandas",
    label: "PandasTools",
    category: "Database",
    importPath: "agno.tools.pandas",
    className: "PandasTools",
    description: "DataFrame operations with pandas.",
  },
  {
    key: "bigquery",
    label: "BigQueryTools",
    category: "Database",
    importPath: "agno.tools.google_bigquery",
    className: "BigQueryTools",
    description: "Integration with Google BigQuery.",
  },
  {
    key: "redshift",
    label: "RedshiftTools",
    category: "Database",
    importPath: "agno.tools.redshift",
    className: "RedshiftTools",
    description: "Integration with AWS Redshift.",
  },
  {
    key: "firecrawl",
    label: "FirecrawlTools",
    category: "Web Scraping",
    importPath: "agno.tools.firecrawl",
    className: "FirecrawlTools",
    description: "Web scraping with Firecrawl.",
  },
  {
    key: "crawl4ai",
    label: "Crawl4AITools",
    category: "Web Scraping",
    importPath: "agno.tools.crawl4ai",
    className: "Crawl4AITools",
    description: "AI-guided crawling.",
  },
  {
    key: "newspaper",
    label: "NewspaperTools",
    category: "Web Scraping",
    importPath: "agno.tools.newspaper",
    className: "NewspaperTools",
    description: "Article extraction with newspaper.",
  },
  {
    key: "newspaper4k",
    label: "Newspaper4kTools",
    category: "Web Scraping",
    importPath: "agno.tools.newspaper4k",
    className: "Newspaper4kTools",
    description: "Article extraction with newspaper4k.",
  },
  {
    key: "jina",
    label: "JinaTools",
    category: "Web Scraping",
    importPath: "agno.tools.jina",
    className: "JinaTools",
    description: "Jina Reader API.",
  },
  {
    key: "spider",
    label: "SpiderTools",
    category: "Web Scraping",
    importPath: "agno.tools.spider",
    className: "SpiderTools",
    description: "Fast crawler for websites.",
  },
  {
    key: "brightdata",
    label: "BrightDataTools",
    category: "Web Scraping",
    importPath: "agno.tools.brightdata",
    className: "BrightDataTools",
    description: "Data collection with BrightData.",
  },
  {
    key: "oxylabs",
    label: "OxylabsTools",
    category: "Web Scraping",
    importPath: "agno.tools.oxylabs",
    className: "OxylabsTools",
    description: "Web scraping and SERP with Oxylabs.",
  },
  {
    key: "arxiv",
    label: "ArxivTools",
    category: "Research",
    importPath: "agno.tools.arxiv",
    className: "ArxivTools",
    description: "Search papers on arXiv.",
  },
  {
    key: "wikipedia",
    label: "WikipediaTools",
    category: "Research",
    importPath: "agno.tools.wikipedia",
    className: "WikipediaTools",
    description: "Search and summarize Wikipedia articles.",
    prerequisite: "pip install wikipedia",
  },
  {
    key: "hackernews",
    label: "HackerNewsTools",
    category: "Research",
    importPath: "agno.tools.hackernews",
    className: "HackerNewsTools",
    description: "Stories and comments from Hacker News.",
  },
  {
    key: "google_calendar",
    label: "GoogleCalendarTools",
    category: "Productivity",
    importPath: "agno.tools.googlecalendar",
    className: "GoogleCalendarTools",
    description: "Google Calendar events and scheduling.",
  },
  {
    key: "google_sheets",
    label: "GoogleSheetsTools",
    category: "Productivity",
    importPath: "agno.tools.googlesheets",
    className: "GoogleSheetsTools",
    description: "Google Sheets spreadsheet operations.",
  },
  {
    key: "google_drive",
    label: "GoogleDriveTools",
    category: "Productivity",
    importPath: "agno.tools.google_drive",
    className: "GoogleDriveTools",
    description: "Google Drive files and folders.",
  },
  {
    key: "notion",
    label: "NotionTools",
    category: "Productivity",
    importPath: "agno.tools.notion",
    className: "NotionTools",
    description: "Notion pages and blocks.",
  },
  {
    key: "todoist",
    label: "TodoistTools",
    category: "Productivity",
    importPath: "agno.tools.todoist",
    className: "TodoistTools",
    description: "Task management in Todoist.",
  },
  {
    key: "trello",
    label: "TrelloTools",
    category: "Productivity",
    importPath: "agno.tools.trello",
    className: "TrelloTools",
    description: "Boards and cards in Trello.",
  },
  {
    key: "linear",
    label: "LinearTools",
    category: "Productivity",
    importPath: "agno.tools.linear",
    className: "LinearTools",
    description: "Issues and projects in Linear.",
  },
  {
    key: "jira",
    label: "JiraTools",
    category: "Productivity",
    importPath: "agno.tools.jira",
    className: "JiraTools",
    description: "Projects and tickets in Jira.",
  },
  {
    key: "confluence",
    label: "ConfluenceTools",
    category: "Productivity",
    importPath: "agno.tools.confluence",
    className: "ConfluenceTools",
    description: "Documentation in Confluence.",
  },
  {
    key: "clickup",
    label: "ClickUpTools",
    category: "Productivity",
    importPath: "agno.tools.clickup",
    className: "ClickUpTools",
    description: "Tasks and spaces in ClickUp.",
  },
  {
    key: "calcom",
    label: "CalComTools",
    category: "Productivity",
    importPath: "agno.tools.calcom",
    className: "CalComTools",
    description: "Scheduling with Cal.com.",
  },
  {
    key: "zoom",
    label: "ZoomTools",
    category: "Productivity",
    importPath: "agno.tools.zoom",
    className: "ZoomTools",
    description: "Meetings and recordings in Zoom.",
  },
  {
    key: "github",
    label: "GithubTools",
    category: "Developer",
    importPath: "agno.tools.github",
    className: "GithubTools",
    description: "GitHub API.",
  },
  {
    key: "bitbucket",
    label: "BitbucketTools",
    category: "Developer",
    importPath: "agno.tools.bitbucket",
    className: "BitbucketTools",
    description: "Repositories and PRs in Bitbucket.",
  },
  {
    key: "shell",
    label: "ShellTools",
    category: "Developer",
    importPath: "agno.tools.shell",
    className: "ShellTools",
    description: "Run shell commands.",
  },
  {
    key: "python",
    label: "PythonTools",
    category: "Developer",
    importPath: "agno.tools.python",
    className: "PythonTools",
    description: "Run Python.",
  },
  {
    key: "docker",
    label: "DockerTools",
    category: "Developer",
    importPath: "agno.tools.docker",
    className: "DockerTools",
    description: "Manage Docker containers.",
  },
  {
    key: "file",
    label: "FileTools",
    category: "Developer",
    importPath: "agno.tools.file",
    className: "FileTools",
    description: "File read/write operations.",
  },
  {
    key: "airflow",
    label: "AirflowTools",
    category: "Developer",
    importPath: "agno.tools.airflow",
    className: "AirflowTools",
    description: "Orchestration with Airflow.",
  },
  {
    key: "aws_lambda",
    label: "AWSLambdaTools",
    category: "Developer",
    importPath: "agno.tools.aws_lambda",
    className: "AWSLambdaTools",
    description: "Invoke and manage AWS Lambda.",
  },
  {
    key: "e2b",
    label: "E2BTools",
    category: "Developer",
    importPath: "agno.tools.e2b",
    className: "E2BTools",
    description: "Code sandboxes with E2B.",
  },
  {
    key: "daytona",
    label: "DaytonaTools",
    category: "Developer",
    importPath: "agno.tools.daytona",
    className: "DaytonaTools",
    description: "Dev environments with Daytona.",
  },
  {
    key: "dalle",
    label: "DalleTools",
    category: "AI & Media",
    importPath: "agno.tools.dalle",
    className: "DalleTools",
    description: "Image generation with DALL-E.",
  },
  {
    key: "replicate",
    label: "ReplicateTools",
    category: "AI & Media",
    importPath: "agno.tools.replicate",
    className: "ReplicateTools",
    description: "Model execution on Replicate.",
  },
  {
    key: "fal",
    label: "FalTools",
    category: "AI & Media",
    importPath: "agno.tools.fal",
    className: "FalTools",
    description: "Fast inference via Fal.",
  },
  {
    key: "lumalabs",
    label: "LumaLabsTools",
    category: "AI & Media",
    importPath: "agno.tools.lumalab",
    className: "LumaLabsTools",
    description: "Multimodal models via Luma Labs.",
  },
  {
    key: "modelslabs",
    label: "ModelsLabsTools",
    category: "AI & Media",
    importPath: "agno.tools.models_labs",
    className: "ModelsLabsTools",
    description: "Multimedia generation with ModelsLab.",
  },
  {
    key: "elevenlabs",
    label: "ElevenLabsTools",
    category: "AI & Media",
    importPath: "agno.tools.eleven_labs",
    className: "ElevenLabsTools",
    description: "Voice synthesis with ElevenLabs.",
  },
  {
    key: "cartesia",
    label: "CartesiaTools",
    category: "AI & Media",
    importPath: "agno.tools.cartesia",
    className: "CartesiaTools",
    description: "Voice and audio with Cartesia.",
  },
  {
    key: "mlx_transcribe",
    label: "MLXTranscribeTools",
    category: "AI & Media",
    importPath: "agno.tools.mlx_transcribe",
    className: "MLXTranscribeTools",
    description: "Local transcription with MLX.",
  },
  {
    key: "youtube",
    label: "YouTubeTools",
    category: "AI & Media",
    importPath: "agno.tools.youtube",
    className: "YouTubeTools",
    description: "YouTube video and channel data.",
  },
  {
    key: "giphy",
    label: "GiphyTools",
    category: "AI & Media",
    importPath: "agno.tools.giphy",
    className: "GiphyTools",
    description: "GIF and short media search.",
  },
  {
    key: "opencv",
    label: "OpenCVTools",
    category: "AI & Media",
    importPath: "agno.tools.opencv",
    className: "OpenCVTools",
    description: "Computer vision operations with OpenCV.",
  },
  {
    key: "calculator",
    label: "CalculatorTools",
    category: "Utility",
    importPath: "agno.tools.calculator",
    className: "CalculatorTools",
    description: "Math operations.",
  },
  {
    key: "sleep",
    label: "SleepTools",
    category: "Utility",
    importPath: "agno.tools.sleep",
    className: "SleepTools",
    description: "Adds controlled delays.",
  },
  {
    key: "openweather",
    label: "OpenWeatherTools",
    category: "Utility",
    importPath: "agno.tools.openweather",
    className: "OpenWeatherTools",
    description: "Weather data.",
  },
  {
    key: "google_maps",
    label: "GoogleMapsTools",
    category: "Utility",
    importPath: "agno.tools.google_maps",
    className: "GoogleMapsTools",
    description: "Maps and routes.",
  },
  {
    key: "visualization",
    label: "VisualizationTools",
    category: "Utility",
    importPath: "agno.tools.visualization",
    className: "VisualizationTools",
    description: "Chart and plot creation.",
  },
  {
    key: "webbrowser",
    label: "WebBrowserTools",
    category: "Utility",
    importPath: "agno.tools.webbrowser",
    className: "WebBrowserTools",
    description: "Browser automation.",
  },
];

const NO_EXTRA_PIP_REQUIRED =
  "No extra pip package detected beyond Agno in the current runtime. Provider credentials or service setup may still be required.";

const TOOL_PREREQUISITES: Record<string, string> = {
  websearch: "pip install ddgs",
  duckduckgo: "pip install ddgs",
  yfinance: "pip install yfinance",
  openbb: "pip install 'openbb'",
  financial_datasets: NO_EXTRA_PIP_REQUIRED,
  postgres: "pip install psycopg-binary",
  duckdb: "pip install duckdb",
  neo4j: "pip install neo4j",
  sql: "pip install sqlalchemy",
  csv: NO_EXTRA_PIP_REQUIRED,
  pandas: "pip install pandas",
  bigquery: "pip install google-cloud-bigquery",
  redshift: "pip install redshift-connector",
  firecrawl: "pip install firecrawl-py",
  crawl4ai: "pip install crawl4ai",
  newspaper: "pip install newspaper3k lxml_html_clean",
  newspaper4k: "pip install newspaper4k lxml_html_clean",
  jina: NO_EXTRA_PIP_REQUIRED,
  spider: "pip install spider-client",
  brightdata: NO_EXTRA_PIP_REQUIRED,
  oxylabs: "pip install oxylabs",
  arxiv: "pip install arxiv",
  wikipedia: "pip install wikipedia",
  hackernews: NO_EXTRA_PIP_REQUIRED,
  google_calendar: "pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib",
  google_sheets: "pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib",
  google_drive: "pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib",
  notion: "pip install notion-client",
  todoist: "pip install todoist-api-python",
  trello: "pip install py-trello",
  linear: NO_EXTRA_PIP_REQUIRED,
  jira: "pip install jira",
  confluence: "pip install atlassian-python-api",
  clickup: NO_EXTRA_PIP_REQUIRED,
  calcom: "pip install requests pytz",
  zoom: NO_EXTRA_PIP_REQUIRED,
  github: "pip install pygithub",
  bitbucket: NO_EXTRA_PIP_REQUIRED,
  shell: NO_EXTRA_PIP_REQUIRED,
  python: NO_EXTRA_PIP_REQUIRED,
  docker: "pip install docker",
  file: NO_EXTRA_PIP_REQUIRED,
  airflow: NO_EXTRA_PIP_REQUIRED,
  aws_lambda: "pip install boto3",
  e2b: "pip install e2b_code_interpreter",
  daytona: "pip install daytona",
  dalle: NO_EXTRA_PIP_REQUIRED,
  replicate: "pip install replicate",
  fal: "pip install fal-client",
  lumalabs: "pip install lumaai",
  modelslabs: NO_EXTRA_PIP_REQUIRED,
  elevenlabs: "pip install elevenlabs",
  cartesia: "pip install cartesia",
  mlx_transcribe: "pip install mlx-whisper",
  youtube: "pip install youtube_transcript_api",
  giphy: NO_EXTRA_PIP_REQUIRED,
  opencv: "pip install opencv-python",
  calculator: NO_EXTRA_PIP_REQUIRED,
  sleep: NO_EXTRA_PIP_REQUIRED,
  openweather: NO_EXTRA_PIP_REQUIRED,
  google_maps: "pip install googlemaps google-maps-places",
  visualization: NO_EXTRA_PIP_REQUIRED,
  webbrowser: NO_EXTRA_PIP_REQUIRED,
};

export const BUILT_IN_TOOLS: BuiltInToolDefinition[] = RAW_BUILT_IN_TOOLS.map((tool) => ({
  ...tool,
  prerequisite: TOOL_PREREQUISITES[tool.key] ?? tool.prerequisite ?? NO_EXTRA_PIP_REQUIRED,
}));

export const BUILT_IN_TOOL_CATEGORIES = Array.from(
  new Set(BUILT_IN_TOOLS.map((tool) => tool.category)),
);

export function getBuiltInTool(toolKey: string | undefined): BuiltInToolDefinition | undefined {
  return BUILT_IN_TOOLS.find((tool) => tool.key === toolKey);
}
