from __future__ import annotations

from .compiler import compile_graph
from .models import CanvasGraph, ExportProjectResponse, ExportedFile
from .runtime_dependencies import graph_runtime_requirements


def export_project(graph: CanvasGraph) -> ExportProjectResponse:
    code, warnings = compile_graph(graph)
    requirements = "\n".join(graph_runtime_requirements(graph)) + "\n"
    readme = "\n".join(
        [
            f"# {graph.project.name}",
            "",
            "Generated by AgnoLab.",
            "",
            "## Files",
            "",
            "- `main.py`: generated Agno flow",
            "- `requirements.txt`: runtime dependencies",
        ]
    ) + "\n"
    return ExportProjectResponse(
        files=[
            ExportedFile(path="main.py", content=code),
            ExportedFile(path="requirements.txt", content=requirements),
            ExportedFile(path="README.md", content=readme),
        ],
        warnings=warnings,
    )
